"""
Main medical routes — disease info, symptom prediction, drug lookup.
All the core MedAI features live here.
"""
from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from typing import Optional
from pydantic import BaseModel
import redis
import json
import hashlib

from app.core.database import get_db
from app.core.config import settings
from app.core.security import get_current_user
from app.ai.ai_service import disease_info, predict_disease, drug_info, chat_stream
from app.models.models import Disease, Medicine, SearchHistory

router = APIRouter(prefix="/medical", tags=["Medical AI"])

# Redis for caching expensive Meditron calls
try:
    cache = redis.from_url(settings.REDIS_URL, decode_responses=True)
    cache.ping()
    CACHE_ON = True
except Exception:
    CACHE_ON = False
    print("Redis unavailable — caching disabled")

CACHE_TTL = 7200  # Cache for 2 hours


def _cache_key(prefix: str, value: str) -> str:
    return f"medai:{prefix}:{hashlib.md5(value.lower().strip().encode()).hexdigest()}"


# ── DISEASE ENDPOINT ──────────────────────────────────────────
@router.get("/disease")
async def get_disease_info(
    name: str = Query(..., min_length=2, description="Disease name e.g. 'Type 2 Diabetes'"),
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Get complete disease information including:
    - What the disease is
    - Symptoms to watch for  
    - Medications to take (with explanations)
    - Medications to avoid (with reasons)
    - Foods to eat (with Indian names)
    - Foods to strictly avoid
    - Lifestyle tips
    All generated by Meditron 70B grounded in RAG medical context.
    """
    key = _cache_key("disease", name)
    
    # Check cache first — Meditron takes 10-30s, cache makes it instant
    if CACHE_ON and (cached := cache.get(key)):
        return json.loads(cached)

    result = disease_info(name)
    
    # Save to cache
    if CACHE_ON:
        cache.setex(key, CACHE_TTL, json.dumps(result))
    
    # Log to search history
    if current_user:
        db.add(SearchHistory(
            user_id=current_user["user_id"],
            query=name,
            query_type="disease"
        ))
        db.commit()

    return result


# ── SYMPTOM PREDICTION ENDPOINT ───────────────────────────────
class SymptomsIn(BaseModel):
    symptoms: list[str]

@router.post("/symptoms/predict")
async def predict_from_symptoms(
    data: SymptomsIn,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Symptom → Disease prediction.
    User enters symptoms like ["fatigue", "frequent urination", "blurred vision"].
    Returns top 3 possible conditions with confidence levels.
    """
    if not data.symptoms:
        raise HTTPException(400, "Please provide at least one symptom")
    if len(data.symptoms) > 15:
        raise HTTPException(400, "Too many symptoms (max 15)")

    symptoms_key = ",".join(sorted([s.lower().strip() for s in data.symptoms]))
    key = _cache_key("symptoms", symptoms_key)
    
    if CACHE_ON and (cached := cache.get(key)):
        return json.loads(cached)

    result = predict_disease(data.symptoms)
    
    if CACHE_ON:
        cache.setex(key, CACHE_TTL, json.dumps(result))

    if current_user:
        db.add(SearchHistory(
            user_id=current_user["user_id"],
            query=", ".join(data.symptoms),
            query_type="symptom"
        ))
        db.commit()

    return result


# ── DRUG INFO ENDPOINT ────────────────────────────────────────
@router.get("/drug")
async def get_drug_info(
    name: str = Query(..., min_length=2, description="Drug name e.g. 'Metformin'"),
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Drug/medicine information lookup.
    User types medicine name → gets complete drug profile.
    """
    key = _cache_key("drug", name)
    
    if CACHE_ON and (cached := cache.get(key)):
        return json.loads(cached)

    # Check local database first for structured data
    db_medicine = (
        db.query(Medicine)
        .filter(Medicine.generic_name.ilike(f"%{name}%"))
        .first()
    )

    result = drug_info(name)
    
    # Enrich with structured database data if found
    if db_medicine:
        result["structured_data"] = {
            "generic_name": db_medicine.generic_name,
            "brand_names": db_medicine.brand_names,
            "drug_class": db_medicine.drug_class,
            "is_otc": db_medicine.is_otc,
            "pregnancy_category": db_medicine.pregnancy_category,
            "common_side_effects": db_medicine.common_side_effects,
        }

    if CACHE_ON:
        cache.setex(key, CACHE_TTL, json.dumps(result))

    if current_user:
        db.add(SearchHistory(
            user_id=current_user["user_id"],
            query=name,
            query_type="drug"
        ))
        db.commit()

    return result


# ── AI CHAT STREAMING ENDPOINT ────────────────────────────────
class ChatIn(BaseModel):
    message: str
    history: list[dict] = []
    user_conditions: list[str] = []
    pregnancy: bool = False

@router.post("/chat/stream")
async def chat_stream_endpoint(
    data: ChatIn,
    current_user: dict = Depends(get_current_user)
):
    """
    Streaming medical AI chat.
    Returns Server-Sent Events (SSE) — text appears word by word in the app.
    """
    if not data.message.strip():
        raise HTTPException(400, "Message cannot be empty")

    async def generate():
        async for chunk in chat_stream(
            message=data.message,
            history=data.history,
            user_conditions=data.user_conditions,
            pregnancy=data.pregnancy
        ):
            yield f"data: {chunk}\n\n"
        yield "data: [DONE]\n\n"

    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"}
    )


# ── SEARCH SUGGESTIONS ────────────────────────────────────────
@router.get("/search/suggestions")
async def get_suggestions(q: str = Query(..., min_length=1), db: Session = Depends(get_db)):
    """Auto-complete suggestions as user types in search bar"""
    diseases = (
        db.query(Disease.name, Disease.common_name, Disease.category)
        .filter(Disease.name.ilike(f"%{q}%"))
        .limit(5)
        .all()
    )
    medicines = (
        db.query(Medicine.generic_name, Medicine.drug_class)
        .filter(Medicine.generic_name.ilike(f"%{q}%"))
        .limit(5)
        .all()
    )
    return {
        "diseases": [{"name": d.name, "common_name": d.common_name, "category": d.category} for d in diseases],
        "medicines": [{"name": m.generic_name, "class": m.drug_class} for m in medicines]
    }


# ── USER SEARCH HISTORY ───────────────────────────────────────
@router.get("/history")
async def get_history(
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Get user's recent searches for the history/recents section"""
    history = (
        db.query(SearchHistory)
        .filter(SearchHistory.user_id == current_user["user_id"])
        .order_by(SearchHistory.created_at.desc())
        .limit(20)
        .all()
    )
    return [{"query": h.query, "type": h.query_type, "time": h.created_at} for h in history]
