"""
Main medical routes — disease info, symptom prediction, drug lookup.
All the core MedAI features live here.
"""
from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import StreamingResponse
from typing import Optional
from pydantic import BaseModel
import redis
import json
import hashlib

from app.core.config import settings
from app.ai.ai_service import disease_info, predict_disease, drug_info, chat_stream

router = APIRouter(prefix="/medical", tags=["Medical AI"])

# Redis for caching expensive Meditron calls
try:
    cache = redis.from_url(settings.REDIS_URL, decode_responses=True)
    cache.ping()
    CACHE_ON = True
except Exception:
    CACHE_ON = False
    print("Redis unavailable — caching disabled")

CACHE_TTL = 7200  # Cache for 2 hours


def _cache_key(prefix: str, value: str) -> str:
    return f"medai:{prefix}:{hashlib.md5(value.lower().strip().encode()).hexdigest()}"


# ── DISEASE ENDPOINT ──────────────────────────────────────────
@router.get("/disease")
async def get_disease_info(
    name: str = Query(..., min_length=2, description="Disease name e.g. 'Type 2 Diabetes'")
):
    """
    Get complete disease information including:
    - What the disease is
    - Symptoms to watch for  
    - Medications to take (with explanations)
    - Medications to avoid (with reasons)
    - Foods to eat (with Indian names)
    - Foods to strictly avoid
    - Lifestyle tips
    All generated by Meditron 70B grounded in RAG medical context.
    """
    key = _cache_key("disease", name)
    
    # Check cache first — Meditron takes 10-30s, cache makes it instant
    if CACHE_ON and (cached := cache.get(key)):
        data = json.loads(cached)
        return {
            "disease": name,
            "response": data.get("content", str(data)),
            "data": data
        }

    data = disease_info(name)
    
    # Save to cache
    if CACHE_ON:
        cache.setex(key, CACHE_TTL, json.dumps(data))

    return {
        "disease": name,
        "response": data.get("content", str(data)),
        "data": data
    }


# ── SYMPTOM PREDICTION ENDPOINT ───────────────────────────────
class SymptomsIn(BaseModel):
    symptoms: list[str]

@router.post("/symptoms/predict")
async def predict_from_symptoms(
    data: SymptomsIn
):
    """
    Symptom → Disease prediction.
    User enters symptoms like ["fatigue", "frequent urination", "blurred vision"].
    Returns top 3 possible conditions with confidence levels.
    """
    if not data.symptoms:
        raise HTTPException(400, "Please provide at least one symptom")
    if len(data.symptoms) > 15:
        raise HTTPException(400, "Too many symptoms (max 15)")

    symptoms_key = ",".join(sorted([s.lower().strip() for s in data.symptoms]))
    key = _cache_key("symptoms", symptoms_key)
    
    if CACHE_ON and (cached := cache.get(key)):
        result = json.loads(cached)
        return {
            "symptoms": data.symptoms,
            "response": result.get("analysis", str(result)),
            "data": result
        }

    result = predict_disease(data.symptoms)
    
    if CACHE_ON:
        cache.setex(key, CACHE_TTL, json.dumps(result))

    return {
        "symptoms": data.symptoms,
        "response": result.get("analysis", str(result)),
        "data": result
    }


# ── DRUG INFO ENDPOINT ────────────────────────────────────────
@router.get("/drug")
async def get_drug_info(
    name: str = Query(..., min_length=2, description="Drug name e.g. 'Metformin'")
):
    """
    Drug/medicine information lookup.
    User types medicine name → gets complete drug profile.
    """
    key = _cache_key("drug", name)
    
    if CACHE_ON and (cached := cache.get(key)):
        data = json.loads(cached)
        return {
            "drug": name,
            "response": data.get("content", str(data)),
            "data": data
        }

    data = drug_info(name)
    
    if CACHE_ON:
        cache.setex(key, CACHE_TTL, json.dumps(data))

    return {
        "drug": name,
        "response": data.get("content", str(data)),
        "data": data
    }


# ── AI CHAT STREAMING ENDPOINT ────────────────────────────────
class ChatIn(BaseModel):
    message: str
    history: list[dict] = []
    user_conditions: list[str] = []
    pregnancy: bool = False

@router.post("/chat/stream")
async def chat_stream_endpoint(
    data: ChatIn
):
    """
    Streaming medical AI chat.
    Returns Server-Sent Events (SSE) — text appears word by word in the app.
    """
    if not data.message.strip():
        raise HTTPException(400, "Message cannot be empty")

    async def generate():
        async for chunk in chat_stream(
            message=data.message,
            history=data.history,
            user_conditions=data.user_conditions,
            pregnancy=data.pregnancy
        ):
            yield f"data: {chunk}\n\n"
        yield "data: [DONE]\n\n"

    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"}
    )


# ── SEARCH SUGGESTIONS ────────────────────────────────────────
@router.get("/search/suggestions")
async def get_suggestions(q: str = Query(..., min_length=1)):
    """Auto-complete suggestions as user types in search bar"""
    return {
        "diseases": [],
        "medicines": [],
        "message": "Search by entering disease or medicine names"
    }

